version: "3.1"

networks:
    docker_network:
        driver: bridge

services:
    www:
        networks:
            - docker_network
        container_name: "php-5.6"
        hostname: "docker-php"
        build:
            context: .docker
#        restart: always
        volumes:
            - ./:/var/www/html
            - ./.docker/apache.conf:/etc/apache2/sites-enabled/000-default.conf
            - ./.docker/php.ini:/usr/local/etc/php/php.ini
        ports:
            - 8056:80
